name: Steps workflow
on: push
jobs:
  backup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: exit 1
      - name: backup-step
        if: failure()
        run: echo backup
